# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_portal', '0003_auto_20170228_0550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
